"use client";

import { type FormEvent, useCallback, useEffect, useState } from "react";
import { Delete01Icon, Logout01Icon, PlusSignIcon } from "@hugeicons/core-free-icons";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";
import { api, type FAQ } from "@/lib/api";

export default function AdminDashboardPage() {
  const router = useRouter(); const [faqs, setFaqs] = useState<FAQ[]>([]); const [questionCount, setQuestionCount] = useState(0); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const [faqData, questions] = await Promise.all([api.faqs(), api.questions()]); setFaqs(faqData); setQuestionCount(questions.length); } catch { router.replace("/admin"); } }, [router]);
  useEffect(() => { void api.verify().then(() => load()).catch(() => router.replace("/admin")); }, [load, router]);
  async function addFaq(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); const form = new FormData(event.currentTarget); try { await api.createFaq({ question: String(form.get("question") ?? ""), answer: String(form.get("answer") ?? ""), category: String(form.get("category") ?? "general"), order_index: faqs.length }); event.currentTarget.reset(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "FAQ could not be saved."); } finally { setBusy(false); } }
  async function removeFaq(id: string) { try { await api.deleteFaq(id); setFaqs((current) => current.filter((faq) => faq.id !== id)); } catch (reason) { setError(reason instanceof Error ? reason.message : "FAQ could not be deleted."); } }
  async function logout() { await api.logout().catch(() => undefined); router.replace("/admin"); }
  return <main className="page page-tight"><div className="section-heading-row"><div className="section-heading"><p className="eyebrow">Content desk</p><h1>Keep the lesson moving.</h1><p className="lede">Manage the reference content that learners meet between simulations.</p></div><button className="button button-dark button-small" type="button" onClick={() => void logout()}><Icon icon={Logout01Icon} size={16} /> Sign out</button></div><div className="admin-grid"><section className="admin-item"><p className="eyebrow">Assessment bank</p><h2 style={{ marginTop: 10 }}>{questionCount} questions</h2><p>Multiple-choice questions are scored by the API. Drag-and-drop content remains available through the seeded bank.</p></section><section className="admin-item"><p className="eyebrow">FAQs</p><h2 style={{ marginTop: 10 }}>{faqs.length} entries</h2><p>Keep answers short enough to support a focused Learn and About experience.</p></section></div><section className="admin-item" style={{ marginTop: 18 }}><div className="section-heading"><p className="eyebrow">Add an entry</p><h2>Publish a useful answer.</h2></div><form className="form-grid" onSubmit={addFaq}><div className="field"><label htmlFor="question">Question</label><input id="question" name="question" required maxLength={500} /></div><div className="field"><label htmlFor="answer">Answer</label><textarea id="answer" name="answer" required maxLength={10000} /></div><div className="field"><label htmlFor="category">Category</label><input id="category" name="category" defaultValue="general" maxLength={100} /></div>{error ? <p className="form-message error" role="alert">{error}</p> : null}<button className="button button-primary" disabled={busy} type="submit"><Icon icon={PlusSignIcon} size={17} /> {busy ? "Saving…" : "Save FAQ"}</button></form></section><section className="admin-item" style={{ marginTop: 18 }}><p className="eyebrow">Published FAQs</p><div className="admin-list">{faqs.map((faq) => <div className="admin-row" key={faq.id}><span><strong>{faq.question}</strong><br /><small className="muted">{faq.category ?? "general"}</small></span><button className="icon-button" type="button" aria-label={`Delete ${faq.question}`} onClick={() => void removeFaq(faq.id)}><Icon icon={Delete01Icon} size={17} /></button></div>)}</div></section></main>;
}
